def get_chatbot_response(user_message):
    """
    Returns a rule-based response for the chatbot.
    Safe, deterministic, and requires no external API keys.
    """
    msg = user_message.lower().strip()
    words = set(msg.split()) # Tokenize for word-based matching
    
    # Helper to check if any keyword matches
    def has_keyword(keywords):
        return any(k in words for k in keywords) or any(k in msg for k in keywords if " " in k)

    # Rule 1: Greetings
    if has_keyword(["hello", "hi", "hey", "greetings", "start"]):
        return "Hello! I am your Deepfake Detection Assistant. Ask me about how to use this tool, what deepfakes are, or how to interpret results."

    # Rule 2: Tech Stack / Technologies (Moved up to prioritize over 'use')
    if has_keyword(["tech", "technologies", "stack", "framework", "library", "libraries"]):
        return (
            "Here is our complete technology stack: \n"
            "- **Core AI**: PyTorch, Transformers (Hugging Face). \n"
            "- **Models**: CLIP (ViT-B/32), TimeSformer-K400, Whisper Base, MTCNN. \n"
            "- **Backend**: Python Flask, NumPy, Pillow, Librosa. \n"
            "- **Frontend**: React.js, Vite, Framer Motion, Tailwind-inspired CSS. \n"
            "This stack ensures real-time, high-accuracy detection."
        )

    # Rule 3: Accuracy / Model queries (Moved up)
    if has_keyword(["accurate", "accuracy", "model", "models", "algorithm", "work"]):
        return (
            "We utilize a state-of-the-art ensemble of models: \n"
            "- **Frontend**: React + Vite + Framer Motion (for smooth UI). \n"
            "- **Backend**: Flask + PyTorch. \n"
            "- **Image Analysis**: OpenAI CLIP (semantic) + MTCNN (face detection) + FFT (frequency analysis). \n"
            "- **Video Analysis**: Meta's TimeSformer (temporal attention) + Facial Forensics. \n"
            "- **Audio Analysis**: OpenAI Whisper (spectral forensics). \n"
            "- **Link Analysis**: Heuristic Phishing Detection."
        )

    # Rule 4: Explaining Deepfakes
    if has_keyword(["deepfake", "define", "meaning"]) or "what is" in msg:
        return (
            "A 'Deepfake' is media generated by AI that mimics real people. "
            "Our tool uses advanced forensics (like FFT frequency analysis and facial motion tracking) "
            "to spot these fake patterns that are invisible to the naked eye."
        )

    # Rule 5: How to use / Instructions (Lower priority to avoid matching 'used' in tech queries)
    if has_keyword(["use", "guide", "help", "upload", "instruction"]) or "how to" in msg:
        return (
            "It's easy to use! \n"
            "1. Choose a tab (Image, Video, Audio, or Link). \n"
            "2. Upload your file or paste the URL. \n"
            "3. Wait for the AI analysis. \n"
            "4. View the 'Verdict' and detailed 'Reasons'."
        )

    # Rule 5: Specific Modalities
    if "image" in words:
        return "For images, we analyze pixel irregularities and frequency artifacts that generative AI models (like GANs or Diffusion) often leave behind."
    if "video" in words:
        return "For videos, we look for inconsistent temporal patterns—like unnatural blinking, jittery facial movements, or background warping."
    if "audio" in words:
        return "For audio, we analyze spectral features and voice patterns to detect synthetic vocoders used in voice cloning."

    # Rule 6: Hackathon / About
    if has_keyword(["project", "hackathon", "team", "created", "who"]):
        return "This project was built for the Deepfake Detection Hackathon to help potential victims identify synthetic media and fight misinformation."

    # Fallback
    return (
        "I'm not sure about that specific query. Try asking: \n"
        "- 'How do I use this?' \n"
        "- 'What is a deepfake?' \n"
        "- 'How accurate is the model?'"
    )
